language: ruby

env:
  - SYSTEM_TEST_HEADLESS=true

addons:
  chrome: stable

cache: bundler

before_install:
  # Use Bundler 2
  - gem update --system --no-document
  - gem install bundler --no-document

before_script:
  - bundle exec rails db:setup

script:
  - bundle exec rails test
  - bundle exec rails test:system

branches:
  only:
    - master

notifications:
  email: false
